### ISSUE TITLE
Model-specific problem prevents submit routine to be completed for all changes

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#11]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Submit routine skips rest of the sheet after encountering a problem.

This happens in specific model (Marco Polo, an example setup), not clear yet why.

* reproducible in Marco Polo model
* not reproducible (yet) in other models (i.e. exact cause or conditions not yet pinpointed)

Follow-up in progress, 2 domain workbooks where this happens available internally.

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.8
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): 32 bit
  - [ ] Additional information:

**Comment by samatrhea** [comment]
The issue is related to the fact that there is at least one `ParameterValuesetSubscription` that references a `CompoundParameterType`, hence there should be multiple slots, one for each component, in the Manual value property. There is only one which causes the exception. Most likely the server did not generate this valueset properly. The fix will be made in 2 places:

  - Update the SDK that in the event a valueset has an incorrect amount of slots in one of the value properties it gets fixed so it does not cause problems downstream.
  - Investigate whether the server is generating incorrect `ParameterValuesetSubscription` objects

**Comment by samatrhea** [comment]
The server seems to create an incorrect Manual value on a ParameterSubscriptionValueSet in the case of a composite ParameterType, recorded in issue https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/5
