### ISSUE TITLE
As a user, I would like to have a mechanism that allows me to quickly check if the quantifiable parts of my requirements are satisfied by a certain design solution.

### ISSUE THREAD

**Issue by MSamoil** [RHEAGROUP/CDP4-IME-Community-Edition#182]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the CDP4-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
Validator to be part of SDK

States of compliance:

- unknown - no verification ran yet
- inconclusive - cannot verify because of some reason
- pass - all conditions are passed
- failed -  at least one condition does not pass

For first iteration:
- drag & drop interaction allowing, to drop a parameter onto a parametric constraint and vice versa.
- button in requirements browser to initiate verification
    - evaluator needs to be made
- column in requirements browser to show compliance (3 state)
- icon overlays for constraints indicating linked, tooltip of constraint shows modelcode of the parameter.
- icon overlay for parameter to indicate link
- constraint context menu to unlink (delete relationship)
- parameter context menu to unlink (-)

For further improvement:
- improvements in relationship browser to indicate better the specific types of relationships.
