### ISSUE TITLE
Excluded element usages incorrectly available on option sheet

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#2]
Element usages that are excluded from a specific option are correctly not appearing in e.g. the product tree of that option.

Problem: In the generated option sheet of the option for which an element usage has been included, the EU is however incorrectly available on the option sheet.

See screenshot for example, where subsystem A is excluded from the CP option (reference screenshot from the client), but is appearing on the option sheet (item indicated in red shouldn't be there).

![20180119 cdp4 exclude element usage in model - correct in client](https://user-images.githubusercontent.com/35371313/35152424-baf500e6-fd22-11e7-986b-4a4ec530cdc7.PNG)

![20180119 cdp4 exclude element usage in model - incorrectly included on option sheet](https://user-images.githubusercontent.com/35371313/35152437-c1255d3a-fd22-11e7-8a2f-189d8829cf7b.PNG)

**Comment by samatrhea** [comment]
The [NestedElementTreeGenerator](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/blob/3a39211b174fb266d63adfe2d793352b7f372a8e/CDP4Common/Helpers/NestedElementTreeGenerator.cs) of the CDP4-SDK does option comparison based on object references, The Option sheet generator does not provide the same `Option`  object, so the comparison does not work as expected. The fix is to update the NestedElementTreeGenerator. The source of the problem is reported here: https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues/4
