### ISSUE TITLE
Expression tree in ParametricConstraint dialog still behaves strangely in edge cases.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#230]
Adding a NOT BooleanExpression with an existing Boolean Expression has caused the tree in the ParametricConstraint dialog to behave inconsistently.

**Comment by samatrhea** [comment]
i may need a bit of assistance to figure out what was going wrong to let you know whether this is now fine

**Comment by lxatrhea** [comment]
> 
> 
> i may need a bit of assistance to figure out what was going wrong to let you know whether this is now fine

- In the Requirementsbrowser: Create a RequirementSpecification, add a Requirement and add a ParametricConstraint that contains an AND expression that has two RelationalExpressions.
Save all and open the ParametricConstraint in a Dialog (right mouseclick on Parametric Constraint and "Edit"). The issue was only present in the Dialog window.

- Add another RelationalExpression
- Add another AND expression.
- In the AddExpression popup that is shown, please select the new RelationalExpression and the existing AND expression. 
When you click OK, the new AND expression is created and it is the only top-level expression that is shown in the ParametricConstraint dialog.
In the old version, the new AND the allready existing AND expression were shown as top level expression in the ParametricConstraint dialog.

**Comment by MartinFijneman** [comment]
verified, issue fixed, no quircks in creating according to steps, end result as expected. Moving to done
